version: "3.8"

services:
    backend:
        build: ./backend
        container_name: fan-event-prediction-api
        ports:
            - "8000:8000"
        environment:
            - SECRET_KEY=${SECRET_KEY:-supersecretkey}
            - ALGORITHM=${ALGORITHM:-HS256}
            - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
            - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:8000}
            - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
            - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT:-}
            - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION:-2023-05-15}
            - AZURE_COSMOS_DB_ENDPOINT=${AZURE_COSMOS_DB_ENDPOINT:-}
            - AZURE_COSMOS_DB_KEY=${AZURE_COSMOS_DB_KEY:-}
            - AZURE_COSMOS_DB_DATABASE=${AZURE_COSMOS_DB_DATABASE:-fan_events}
        restart: unless-stopped

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: fan-event-prediction-ui
        ports:
            - "3000:3000"
        environment:
            - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}
        depends_on:
            - backend
        restart: unless-stopped
